### ISSUE TITLE
Error after upgrading ndarray from 0.16.1 to 0.17.1

### ISSUE THREAD

**Issue by alphaville** [argmin-rs/modcholesky#39]
I upgraded `ndarray` from version `0.16.1` to [`0.17.1`](https://crates.io/crates/ndarray/0.17.1), which was released recently, and I'm getting the following error when I try to apply `mod_cholesky_se99` on an instance of `ndarray`:

```
error[E0599]: no method named `mod_cholesky_se99` found for struct `ArrayBase<OwnedRepr<f64>, Dim<[usize; 2]>, f64>` in the current scope
  --> src/constraints/affine_space.rs:54:31
   |
54 |         let res = a_times_a_t.mod_cholesky_se99();
   |                               ^^^^^^^^^^^^^^^^^ method not found in `ArrayBase<OwnedRepr<f64>, Dim<[usize; 2]>, f64>`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `optimization_engine` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `optimization_engine` (lib test) due to 1 previous error
```

Everything works fine with `ndarray` version `0.16.1` (see #34).
