### ISSUE TITLE
Error after upgrading ndarray from 0.15 to 0.16

### ISSUE THREAD

**Issue by alphaville** [argmin-rs/modcholesky#34]
I upgraded `ndarray` from version 0.15 to 0.16 and I'm getting the following error when I try to apply `mod_cholesky_se99` on an instance of `ndarray`:

```
error[E0599]: no method named `mod_cholesky_se99` found for struct `constraints::affine_space::ndarray::ArrayBase` in the current scope
  --> src/constraints/affine_space.rs:54:31
   |
54 |         let res = a_times_a_t.mod_cholesky_se99();
   |                               ^^^^^^^^^^^^^^^^^ method not found in `ArrayBase<OwnedRepr<f64>, Dim<[usize; 2]>>`

```

The same code works with ndarray 0.15.

**Comment by stefan-k** [comment]
`modcholesky` needs to be updated to ndarray 0.16 as well.

**Comment by stefan-k** [comment]
The new version 0.2 with the fix is released.
